import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    // <>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //    <div>
    //     <h1>Hello World</h1>
    //     <p>Parágrafo com React.js</p>
    //     <p>Criado por DevMedia</p>
    //   </div> 
    // </>

    // <footer>
    //   <img src ="" alt ="Clínica Médica" title="Clínica Médica" />
    //   <p>Telefone e WhatsApp: (21) 99966-5555</p>
    //   <p>Endereço: Av. Ayrton Senna, 3000 - Barra da Tijuca, Rio de Janeiro</p>
    //   <p>Clínica Médica Life - Todos os direitos reservados. </p>
    // </footer>

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Hello World</h1>
        <p>Parágrafo com React.js</p>
        <p>Criado por DevMedia</p>
      </div>
    </>
  );
}
